<?php
$color_selector = array(
    'a',
    'a:hover',
    'h1 a:hover',
    'h2 a:hover',
    'h3 a:hover',
    'h4 a:hover',
    'h5 a:hover',
    'h6 a:hover',
    'p a',
    'p a:hover',
    'h1',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6',
    '.eltdf-st-loader .eltdf-loader-title-spinner .eltdf-loader-title-spinner-text',
    '#respond input:focus[type=text]',
    '#respond textarea:focus',
    '.eltdf-style-form textarea:focus',
    '.wpcf7-form-control.wpcf7-date:focus',
    '.wpcf7-form-control.wpcf7-number:focus',
    '.wpcf7-form-control.wpcf7-quiz:focus',
    '.wpcf7-form-control.wpcf7-select:focus',
    '.wpcf7-form-control.wpcf7-text:focus',
    '.wpcf7-form-control.wpcf7-textarea:focus',
    'input:focus[type=text]',
    'input:focus[type=email]',
    'input:focus[type=password]',
    '.eltdf-comment-holder .eltdf-comment-text .comment-edit-link:hover',
    '.eltdf-comment-holder .eltdf-comment-text .comment-reply-link:hover',
    '.eltdf-comment-holder .eltdf-comment-text .replay:hover',
    '.eltdf-comment-holder .eltdf-comment-text #cancel-comment-reply-link:hover',
    '.eltdf-owl-slider .owl-nav .owl-next>span',
    '.eltdf-owl-slider .owl-nav .owl-prev>span',
    '.error404 .eltdf-page-not-found .eltdf-404-form .input-holder button',
    '.error404 .eltdf-page-not-found .eltdf-404-form .input-holder input',
    '.error404 .eltdf-page-not-found .eltdf-404-form .input-holder button',
    '.error404 .eltdf-page-not-found .eltdf-404-form .input-holder button:hover',
    '#eltdf-back-to-top>span:hover',
    'footer .widget ul li a:hover',
    'footer .widget #wp-calendar tfoot a:hover',
    'footer .widget .eltdf-searchform .input-holder button',
    'footer .widget .eltdf-searchform .input-holder input',
    'footer .widget .eltdf-searchform .input-holder button:hover',
    'footer .widget .tagcloud a:hover',
    '.eltdf-fullscreen-sidebar .widget ul li a:hover',
    '.eltdf-fullscreen-sidebar .widget #wp-calendar tfoot a:hover',
    '.eltdf-fullscreen-sidebar .widget .eltdf-searchform .input-holder button',
    '.eltdf-fullscreen-sidebar .widget .eltdf-searchform .input-holder input',
    '.eltdf-fullscreen-sidebar .widget .eltdf-searchform .input-holder button:hover',
    '.eltdf-fullscreen-sidebar .widget .tagcloud a:hover',
    '.eltdf-side-menu #wp-calendar td#today',
    '.eltdf-side-menu .widget.widget_archive select option',
    '.eltdf-side-menu .widget.widget_categories select option',
    '.eltdf-side-menu .widget.widget_text select option',
    '.eltdf-side-menu .widget .eltdf-searchform .input-holder button',
    '.eltdf-side-menu .widget .eltdf-searchform .input-holder input',
    '.wpb_widgetised_column .widget ul li',
    'aside.eltdf-sidebar .widget ul li',
    '.wpb_widgetised_column .widget ul li a',
    '.wpb_widgetised_column .widget ul li a:hover',
    'aside.eltdf-sidebar .widget ul li a',
    'aside.eltdf-sidebar .widget ul li a:hover',
    '.wpb_widgetised_column .widget.widget_archive ul li a',
    '.wpb_widgetised_column .widget.widget_categories ul li a',
    '.wpb_widgetised_column .widget.widget_meta ul li a',
    '.wpb_widgetised_column .widget.widget_nav_menu ul li a',
    '.wpb_widgetised_column .widget.widget_pages ul li a',
    '.wpb_widgetised_column .widget.widget_recent_entries ul li a',
    'aside.eltdf-sidebar .widget.widget_archive ul li a',
    'aside.eltdf-sidebar .widget.widget_categories ul li a',
    'aside.eltdf-sidebar .widget.widget_meta ul li a',
    'aside.eltdf-sidebar .widget.widget_nav_menu ul li a',
    'aside.eltdf-sidebar .widget.widget_pages ul li a',
    'aside.eltdf-sidebar .widget.widget_recent_entries ul li a',
    '.wpb_widgetised_column .widget #wp-calendar tfoot a',
    '.wpb_widgetised_column .widget #wp-calendar tfoot a:hover',
    'aside.eltdf-sidebar .widget #wp-calendar tfoot a',
    'aside.eltdf-sidebar .widget #wp-calendar tfoot a:hover',
    '.wpb_widgetised_column .widget .eltdf-searchform .input-holder button',
    '.wpb_widgetised_column .widget .eltdf-searchform .input-holder input',
    'aside.eltdf-sidebar .widget .eltdf-searchform .input-holder button',
    'aside.eltdf-sidebar .widget .eltdf-searchform .input-holder input',
    '.wpb_widgetised_column .widget .eltdf-searchform .input-holder button:hover',
    'aside.eltdf-sidebar .widget .eltdf-searchform .input-holder button:hover',
    '.wpb_widgetised_column .widget .tagcloud a:hover',
    'aside.eltdf-sidebar .widget .tagcloud a:hover',
    '.eltdf-top-bar .widget a:hover',
    'body .pp_pic_holder #pp_full_res .pp_inline',
    'body .pp_pic_holder a.pp_arrow_next:hover',
    'body .pp_pic_holder a.pp_arrow_previous:hover',
    'body .pp_pic_holder a.pp_next',
    'body .pp_pic_holder a.pp_previous',
    'body .pp_pic_holder a.pp_close:hover',
    'body .select2-container--default.select2-container--open .select2-selection--single',
    'body .select2-container--default .select2-results__option[aria-disabled=true]',
    'body .select2-container--default .select2-results__option[aria-selected=true]',
    'body .select2-container--default .select2-results__option[data-selected=true]',
    'body .select2-container--default .select2-results__option--highlighted[aria-selected]',
    '.widget_icl_lang_sel_widget .wpml-ls-legacy-dropdown .wpml-ls-item-toggle',
    '.widget_icl_lang_sel_widget .wpml-ls-legacy-dropdown-click .wpml-ls-item-toggle',
    '.widget_icl_lang_sel_widget .wpml-ls-legacy-dropdown .wpml-ls-item-toggle:hover',
    '.widget_icl_lang_sel_widget .wpml-ls-legacy-dropdown-click .wpml-ls-item-toggle:hover',
    '.eltdf-blog-holder article.sticky .eltdf-post-title a',
    '.eltdf-blog-holder article .eltdf-post-text .eltdf-post-icon-holder',
    '.eltdf-blog-holder article .eltdf-post-info-top>div a:hover',
    '.eltdf-blog-holder article.format-link .eltdf-post-text .eltdf-post-icon-holder span',
    '.eltdf-blog-holder article.format-link .eltdf-post-mark .eltdf-link-mark',
    '.eltdf-blog-holder article.format-quote .eltdf-post-mark .eltdf-quote-mark',
    '.eltdf-blog-holder article.format-audio .eltdf-post-icon-holder span',
    '.eltdf-blog-holder article.format-video .eltdf-self-hosted-video .mejs-overlay-play .mejs-overlay-button:before',
    '.eltdf-blog-pagination ul li.eltdf-pag-active a',
    '.eltdf-bl-standard-pagination ul li.eltdf-pag-active a',
    '.eltdf-blog-pag-loading',
    '.eltdf-author-description .eltdf-author-description-text-holder .eltdf-author-name a',
    '.eltdf-author-description .eltdf-author-description-text-holder .eltdf-author-name a:hover',
    '.eltdf-author-description .eltdf-author-description-text-holder .eltdf-author-social-icons a',
    '.eltdf-single-links-pages .eltdf-single-links-pages-inner>a:hover',
    '.eltdf-single-links-pages .eltdf-single-links-pages-inner>span',
    '.eltdf-related-posts-holder .eltdf-related-post:nth-child(2n+1) .eltdf-related-post-content .eltdf-related-post-info .eltdf-post-info-category .eltdf-post-info-category-name',
    '.eltdf-blog-list-holder .eltdf-bli-content .eltdf-bli-info-bottom a:hover',
    '.eltdf-blog-list-holder.eltdf-bl-masonry .eltdf-bl-item:nth-child(2n+1) .eltdf-bli-content .eltdf-bli-info .eltdf-post-info-category .eltdf-post-info-category-name',
    '.eltdf-blog-list-holder.eltdf-bl-standard .eltdf-bl-item:nth-child(2n+1) .eltdf-bli-content .eltdf-bli-info .eltdf-post-info-category .eltdf-post-info-category-name',
    '.eltdf-blog-list-holder.eltdf-bl-minimal .eltdf-post-info-date a:hover',
    '.eltdf-blog-list-holder.eltdf-bl-simple .eltdf-bli-content .eltdf-post-info-date a:hover',
    '.eltdf-main-menu>ul>li>a',
    '.eltdf-dark-header .eltdf-page-header>div:not(.eltdf-sticky-header):not(.fixed) .eltdf-main-menu>ul>li>a',
    '.eltdf-dark-header .eltdf-page-header>div:not(.eltdf-sticky-header):not(.fixed) .eltdf-fullscreen-menu-opener',
    '.eltdf-dark-header .eltdf-page-header>div:not(.eltdf-sticky-header):not(.fixed) .eltdf-fullscreen-menu-opener.eltdf-fm-opened',
    '.eltdf-dark-header .eltdf-page-header>div:not(.eltdf-sticky-header):not(.fixed) .eltdf-fullscreen-menu-opener:hover',
    '.eltdf-light-header .eltdf-page-header>div:not(.eltdf-sticky-header):not(.fixed) .eltdf-fullscreen-menu-opener.eltdf-fm-opened',
    '.eltdf-light-header .eltdf-page-header>div:not(.eltdf-sticky-header):not(.fixed) .eltdf-fullscreen-menu-opener:hover',
    '.eltdf-header-vertical .eltdf-vertical-menu ul li a',
    '.eltdf-header-vertical .eltdf-vertical-menu ul li a:hover',
    '.eltdf-header-vertical .eltdf-vertical-menu ul li a .eltdf-menu-featured-icon',
    '.eltdf-mobile-header .eltdf-mobile-menu-opener.eltdf-mobile-menu-opened a',
    '.eltdf-mobile-header .eltdf-mobile-nav .eltdf-grid>ul>li.eltdf-active-item>a',
    '.eltdf-mobile-header .eltdf-mobile-nav .eltdf-grid>ul>li.eltdf-active-item>h6',
    '.eltdf-mobile-header .eltdf-mobile-nav ul li a:hover',
    '.eltdf-mobile-header .eltdf-mobile-nav ul li h6:hover',
    '.eltdf-mobile-header .eltdf-mobile-nav ul ul li.current-menu-ancestor>a',
    '.eltdf-mobile-header .eltdf-mobile-nav ul ul li.current-menu-ancestor>h6',
    '.eltdf-mobile-header .eltdf-mobile-nav ul ul li.current-menu-item>a',
    '.eltdf-mobile-header .eltdf-mobile-nav ul ul li.current-menu-item>h6',
    '.eltdf-mobile-header .eltdf-mobile-nav ul li a',
    '.eltdf-mobile-header .eltdf-mobile-nav ul li h6',
    '.eltdf-search-page-holder .eltdf-search-page-form .eltdf-form-holder .eltdf-search-submit:hover',
    '.eltdf-search-page-holder article.sticky .eltdf-post-title a',
    '.eltdf-search-cover .eltdf-search-close:hover',
    '.eltdf-dark-header .eltdf-page-header>div:not(.eltdf-sticky-header):not(.fixed) .eltdf-side-menu-button-opener',
    '.eltdf-dark-header .eltdf-page-header>div:not(.eltdf-sticky-header):not(.fixed) .eltdf-side-menu-button-opener:not(.eltdf-side-menu-button-opener-predefined).opened',
    '.eltdf-dark-header .eltdf-page-header>div:not(.eltdf-sticky-header):not(.fixed) .eltdf-side-menu-button-opener:not(.eltdf-side-menu-button-opener-predefined):hover',
    '.eltdf-dark-header .eltdf-top-bar .eltdf-side-menu-button-opener',
    '.eltdf-dark-header .eltdf-top-bar .eltdf-side-menu-button-opener:not(.eltdf-side-menu-button-opener-predefined).opened',
    '.eltdf-dark-header .eltdf-top-bar .eltdf-side-menu-button-opener:not(.eltdf-side-menu-button-opener-predefined):hover',
    '.eltdf-light-header .eltdf-page-header>div:not(.eltdf-sticky-header):not(.fixed) .eltdf-side-menu-button-opener:not(.eltdf-side-menu-button-opener-predefined).opened',
    '.eltdf-light-header .eltdf-page-header>div:not(.eltdf-sticky-header):not(.fixed) .eltdf-side-menu-button-opener:not(.eltdf-side-menu-button-opener-predefined):hover',
    '.eltdf-light-header .eltdf-top-bar .eltdf-side-menu-button-opener:not(.eltdf-side-menu-button-opener-predefined).opened',
    '.eltdf-light-header .eltdf-top-bar .eltdf-side-menu-button-opener:not(.eltdf-side-menu-button-opener-predefined):hover',
    '.eltdf-side-menu-button-opener.opened',
    '.eltdf-side-menu-button-opener:hover',
    '.eltdf-side-menu-button-opener.eltdf-side-menu-button-opener-predefined .eltdf-hm-lines',
    '.eltdf-subscribe-popup-holder .eltdf-sp-close',
    '.eltdf-title-holder.eltdf-breadcrumbs-type .eltdf-breadcrumbs a:hover',
    '.eltdf-title-holder.eltdf-standard-with-breadcrumbs-type .eltdf-breadcrumbs a:hover',
    '.widget.eltdf-search-post-type-widget .eltdf-search-icon',
    '.widget.eltdf-search-post-type-widget .eltdf-search-loading',
    '.eltdf-social-icons-group-widget.eltdf-square-icons .eltdf-social-icon-widget-holder:hover',
    '.eltdf-social-icons-group-widget.eltdf-square-icons.eltdf-light-skin .eltdf-social-icon-widget-holder',
    '.eltdf-social-icons-group-widget.eltdf-square-icons.eltdf-light-skin .eltdf-social-icon-widget-holder:hover',
    '.eltdf-portfolio-single-holder .eltdf-ps-info-holder .eltdf-ps-info-item .eltdf-ps-info-category',
    '.eltdf-portfolio-single-holder .eltdf-ps-info-holder .eltdf-ps-info-item .eltdf-ps-info-date',
    '.eltdf-portfolio-single-holder .eltdf-ps-info-holder .eltdf-ps-info-item .eltdf-ps-info-tag',
    '.widget.eltdf-featured-projects-widget .eltdf-featured-project-opener.eltdf-fpo-button-opener-predefined .eltdf-hm-lines',
    '.widget.eltdf-featured-projects-widget .eltdf-featured-project-holder.eltdf-fpw-skin-light .eltdf-featured-project-close',
    '.eltdf-pl-filter-holder ul li span',
    '.eltdf-pl-filter-holder ul li.eltdf-pl-current span',
    '.eltdf-pl-filter-holder ul li:hover span',
    '.eltdf-pl-standard-pagination ul li.eltdf-pag-active a',
    '.eltdf-pl-loading',
    '.eltdf-portfolio-list-holder.eltdf-pl-gallery-overlay article .eltdf-pli-text .eltdf-pli-category-holder a:hover',
    '.eltdf-portfolio-project-info>div',
    '.eltdf-portfolio-slider-holder .eltdf-portfolio-list-holder.eltdf-nav-dark-skin .owl-nav .owl-next',
    '.eltdf-portfolio-slider-holder .eltdf-portfolio-list-holder.eltdf-nav-dark-skin .owl-nav .owl-next:hover',
    '.eltdf-portfolio-slider-holder .eltdf-portfolio-list-holder.eltdf-nav-dark-skin .owl-nav .owl-prev',
    '.eltdf-portfolio-slider-holder .eltdf-portfolio-list-holder.eltdf-nav-dark-skin .owl-nav .owl-prev:hover',
    '.eltdf-portfolio-slider-holder .eltdf-portfolio-list-holder.eltdf-nav-light-skin .owl-nav .owl-next:hover',
    '.eltdf-portfolio-slider-holder .eltdf-portfolio-list-holder.eltdf-nav-light-skin .owl-nav .owl-prev:hover',
    '.eltdf-testimonials-holder .owl-nav .owl-next span',
    '.eltdf-testimonials-holder .owl-nav .owl-prev span',
    '.eltdf-reviews-per-criteria .eltdf-item-reviews-average-rating',
    '.eltdf-banner-holder .eltdf-banner-link-text .eltdf-banner-link-hover span',
    '.eltdf-btn.eltdf-btn-outline',
    '.eltdf-countdown .countdown-row .countdown-section .countdown-amount',
    '.eltdf-counter-holder .eltdf-counter',
    '.eltdf-expanding-carousel-holder .eltdf-esc-nav .eltdf-esc-nav-next',
    '.eltdf-expanding-carousel-holder .eltdf-esc-nav .eltdf-esc-nav-prev',
    '.eltdf-full-screen-image-slider .eltdf-fsis-slider .owl-dots .owl-dot.active',
    '.eltdf-full-screen-image-slider .eltdf-fsis-slider .owl-dots .owl-dot:hover',
    '.eltdf-full-screen-sections .eltdf-fss-nav-holder a',
    '.eltdf-dark-header .eltdf-full-screen-sections .eltdf-fss-nav-holder a',
    '.eltdf-icon-list-holder .eltdf-il-icon-holder>*',
    '.eltdf-image-gallery .eltdf-ig-custom-title',
    '.eltdf-image-highlight-holder span.eltdf-ih-title',
    '.eltdf-pie-chart-holder .eltdf-pc-percentage .eltdf-pc-percent',
    '.eltdf-price-table .eltdf-pt-inner ul li.eltdf-pt-title-holder',
    '.eltdf-price-table .eltdf-pt-inner ul li.eltdf-pt-prices .eltdf-pt-value',
    '.eltdf-price-table .eltdf-pt-inner ul li.eltdf-pt-prices .eltdf-pt-price',
    '.eltdf-social-share-holder.eltdf-list li a',
    '.eltdf-social-share-holder.eltdf-dropdown .eltdf-social-share-dropdown-opener .social_share',
    '.eltdf-social-share-holder.eltdf-dropdown .eltdf-social-share-dropdown-opener:hover',
    '.eltdf-tabs.eltdf-tabs-standard .eltdf-tabs-nav li a',
    '.eltdf-tabs.eltdf-tabs-boxed .eltdf-tabs-nav li a',
    '.eltdf-tabs.eltdf-tabs-simple .eltdf-tabs-nav li a',
    '.eltdf-tabs.eltdf-tabs-simple .eltdf-tabs-nav li.ui-state-active a',
    '.eltdf-tabs.eltdf-tabs-simple .eltdf-tabs-nav li.ui-state-hover a',
    '.eltdf-tabs.eltdf-tabs-vertical .eltdf-tabs-nav li a',
    '.eltdf-tabs.eltdf-tabs-vertical .eltdf-tabs-nav li.ui-state-active a',
    '.eltdf-tabs.eltdf-tabs-vertical .eltdf-tabs-nav li.ui-state-hover a',
    '.eltdf-text-marquee',
    '.eltdf-video-button-holder .eltdf-video-button-play',
    '.eltdf-instagram-feed.eltdf-instagram-carousel .owl-item li a .eltdf-instagram-icon',
    '.eltdf-twitter-list-holder .eltdf-twitter-icon',
    '.eltdf-twitter-list-holder .eltdf-tweet-text a:hover',
    '.eltdf-twitter-list-holder .eltdf-twitter-profile a:hover',
    '.widget.widget_eltdf_twitter_widget .eltdf-twitter-widget li .eltdf-twitter-icon',
    '.widget.widget_eltdf_twitter_widget .eltdf-twitter-widget li .eltdf-tweet-text a:hover'
);
$color_important_selector = array(
    '.eltdf-light-header .eltdf-page-header>div:not(.fixed):not(.eltdf-sticky-header) .eltdf-menu-area .widget a:hover',
    '.eltdf-dark-header .eltdf-page-header>div:not(.fixed):not(.eltdf-sticky-header) .eltdf-menu-area',
    '.eltdf-dark-header .eltdf-page-header>div:not(.fixed):not(.eltdf-sticky-header) .eltdf-menu-area .widget',
    '.eltdf-dark-header .eltdf-page-header>div:not(.fixed):not(.eltdf-sticky-header) .eltdf-menu-area .widget .widgettitle',
    '.eltdf-dark-header .eltdf-page-header>div:not(.fixed):not(.eltdf-sticky-header) .eltdf-menu-area .widget a',
    '.eltdf-dark-header .eltdf-page-header>div:not(.fixed):not(.eltdf-sticky-header) .eltdf-menu-area .widget a:hover',
    '.eltdf-dark-header .eltdf-page-header>div:not(.fixed):not(.eltdf-sticky-header) .eltdf-menu-area .widget i',
    '.eltdf-dark-header .eltdf-page-header>div:not(.fixed):not(.eltdf-sticky-header) .eltdf-menu-area .widget p',
    '.eltdf-dark-header .eltdf-page-header>div:not(.fixed):not(.eltdf-sticky-header) .eltdf-menu-area .widget span',
    '.eltdf-dark-header .eltdf-page-header>div:not(.fixed):not(.eltdf-sticky-header).eltdf-menu-area',
    '.eltdf-dark-header .eltdf-page-header>div:not(.fixed):not(.eltdf-sticky-header).eltdf-menu-area .widget',
    '.eltdf-dark-header .eltdf-page-header>div:not(.fixed):not(.eltdf-sticky-header).eltdf-menu-area .widget .widgettitle',
    '.eltdf-dark-header .eltdf-page-header>div:not(.fixed):not(.eltdf-sticky-header).eltdf-menu-area .widget a',
    '.eltdf-dark-header .eltdf-page-header>div:not(.fixed):not(.eltdf-sticky-header).eltdf-menu-area .widget a:hover',
    '.eltdf-dark-header .eltdf-page-header>div:not(.fixed):not(.eltdf-sticky-header).eltdf-menu-area .widget i',
    '.eltdf-dark-header .eltdf-page-header>div:not(.fixed):not(.eltdf-sticky-header).eltdf-menu-area .widget p',
    '.eltdf-dark-header .eltdf-page-header>div:not(.fixed):not(.eltdf-sticky-header).eltdf-menu-area .widget span',
    '.eltdf-light-header .eltdf-page-header>div:not(.fixed):not(.eltdf-sticky-header).eltdf-menu-area .widget a:hover',
    '.eltdf-dark-header.eltdf-header-vertical .eltdf-vertical-menu ul li a',
    '.eltdf-dark-header.eltdf-header-vertical .eltdf-vertical-menu ul li a:hover',
    '.eltdf-dark-header.eltdf-header-vertical .eltdf-vertical-menu ul li ul li.current-menu-ancestor>a',
    '.eltdf-dark-header.eltdf-header-vertical .eltdf-vertical-menu ul li ul li.current-menu-item>a',
    '.eltdf-dark-header.eltdf-header-vertical .eltdf-vertical-menu ul li ul li.current_page_item>a',
    '.eltdf-dark-header.eltdf-header-vertical .eltdf-vertical-menu>ul>li.current-menu-ancestor>a',
    '.eltdf-dark-header.eltdf-header-vertical .eltdf-vertical-menu>ul>li.eltdf-active-item>a',
    '.eltdf-light-header.eltdf-header-vertical .eltdf-vertical-menu ul li a:hover',
    '.eltdf-light-header.eltdf-header-vertical .eltdf-vertical-menu ul li ul li.current-menu-ancestor>a',
    '.eltdf-light-header.eltdf-header-vertical .eltdf-vertical-menu ul li ul li.current-menu-item>a',
    '.eltdf-light-header.eltdf-header-vertical .eltdf-vertical-menu ul li ul li.current_page_item>a',
    '.eltdf-light-header.eltdf-header-vertical .eltdf-vertical-menu>ul>li.current-menu-ancestor>a',
    '.eltdf-light-header.eltdf-header-vertical .eltdf-vertical-menu>ul>li.eltdf-active-item>a',
    '.eltdf-dark-header .eltdf-page-header>div:not(.eltdf-sticky-header):not(.fixed) .eltdf-search-opener',
    '.eltdf-dark-header .eltdf-page-header>div:not(.eltdf-sticky-header):not(.fixed) .eltdf-search-opener:hover',
    '.eltdf-dark-header .eltdf-top-bar .eltdf-search-opener',
    '.eltdf-dark-header .eltdf-top-bar .eltdf-search-opener:hover',
    '.eltdf-dark-header .eltdf-page-header>div:not(.eltdf-sticky-header):not(.fixed) .eltdf-icon-widget-holder',
    '.eltdf-dark-header .eltdf-page-header>div:not(.eltdf-sticky-header):not(.fixed) .eltdf-icon-widget-holder:hover',
    '.eltdf-light-header .eltdf-page-header>div:not(.eltdf-sticky-header):not(.fixed) .eltdf-icon-widget-holder:hover',
    '.eltdf-dark-header .eltdf-page-header>div:not(.eltdf-sticky-header):not(.fixed) .eltdf-social-icon-widget-holder',
    '.eltdf-dark-header .eltdf-page-header>div:not(.eltdf-sticky-header):not(.fixed) .eltdf-social-icon-widget-holder:hover',
    '.eltdf-light-header .eltdf-page-header>div:not(.eltdf-sticky-header):not(.fixed) .eltdf-social-icon-widget-holder:hover',
    '.eltdf-light-header .eltdf-page-header>div:not(.fixed):not(.eltdf-sticky-header) .eltdf-menu-area .widget.eltdf-featured-projects-widget .eltdf-featured-project-holder.eltdf-fpw-skin-light .eltdf-featured-project-close',
    '.eltdf-light-header .eltdf-page-header>div:not(.fixed):not(.eltdf-sticky-header) .eltdf-menu-area .widget.eltdf-featured-projects-widget .eltdf-featured-project-holder.eltdf-fpw-skin-light .eltdf-featured-project-close span',
    '.eltdf-light-header .eltdf-page-header>div:not(.fixed):not(.eltdf-sticky-header).eltdf-menu-area .widget.eltdf-featured-projects-widget .eltdf-featured-project-holder.eltdf-fpw-skin-light .eltdf-featured-project-close',
    '.eltdf-light-header .eltdf-page-header>div:not(.fixed):not(.eltdf-sticky-header).eltdf-menu-area .widget.eltdf-featured-projects-widget .eltdf-featured-project-holder.eltdf-fpw-skin-light .eltdf-featured-project-close span',
    '.widget.eltdf-featured-projects-widget .eltdf-featured-project-holder.eltdf-fpw-skin-light .eltdf-portfolio-list-holder article .eltdf-pli-text .eltdf-pli-category-holder a',
    '.widget.eltdf-featured-projects-widget .eltdf-featured-project-holder.eltdf-fpw-skin-light .eltdf-portfolio-list-holder article .eltdf-pli-text .eltdf-pli-title span',
    '.eltdf-btn.eltdf-btn-simple:not(.eltdf-btn-custom-hover-color):hover',
    '.eltdf-btn.eltdf-btn-solid:not(.eltdf-btn-custom-hover-color):hover'
);
$background_color_selector = array(
    '.eltdf-st-loader .pulse',
    '.eltdf-st-loader .double_pulse .double-bounce1',
    '.eltdf-st-loader .double_pulse .double-bounce2',
    '.eltdf-st-loader .cube',
    '.eltdf-st-loader .rotating_cubes .cube1',
    '.eltdf-st-loader .rotating_cubes .cube2',
    '.eltdf-st-loader .stripes>div',
    '.eltdf-st-loader .wave>div',
    '.eltdf-st-loader .two_rotating_circles .dot1',
    '.eltdf-st-loader .two_rotating_circles .dot2',
    '.eltdf-st-loader .five_rotating_circles .spinner-container>div',
    '.eltdf-st-loader .atom .ball-1:before',
    '.eltdf-st-loader .atom .ball-2:before',
    '.eltdf-st-loader .atom .ball-3:before',
    '.eltdf-st-loader .atom .ball-4:before',
    '.eltdf-st-loader .clock .ball:before',
    '.eltdf-st-loader .mitosis .ball',
    '.eltdf-st-loader .lines .line1',
    '.eltdf-st-loader .lines .line2',
    '.eltdf-st-loader .lines .line3',
    '.eltdf-st-loader .lines .line4',
    '.eltdf-st-loader .fussion .ball',
    '.eltdf-st-loader .wave_circles .ball',
    '.eltdf-st-loader .pulse_circles .ball',
    '#submit_comment:hover',
    '.post-password-form input[type=submit]:hover',
    'input.wpcf7-form-control.wpcf7-submit:hover',
    '.eltdf-owl-slider .owl-dots .owl-dot.active span:not(.eltdf-owl-pag-name)',
    '.eltdf-owl-slider .owl-dots .owl-dot:hover span:not(.eltdf-owl-pag-name)',
    '#eltdf-back-to-top>span',
    'footer .widget #wp-calendar td#today',
    '.eltdf-fullscreen-sidebar .widget #wp-calendar td#today',
    '.eltdf-side-menu .widget #wp-calendar td#today',
    '.wpb_widgetised_column .widget #wp-calendar td#today',
    'aside.eltdf-sidebar .widget #wp-calendar td#today',
    '#ui-datepicker-div .ui-widget-header',
    'body .pp_overlay',
    'body .select2-container--default .select2-selection--multiple .select2-selection__rendered .select2-selection__choice',
    '.eltdf-blog-holder article.format-audio .eltdf-blog-audio-holder .mejs-container',
    '.eltdf-bl-standard-pagination ul li a:after',
    '.eltdf-bl-standard-pagination ul li.eltdf-pag-active a:after',
    '.eltdf-blog-pagination ul li a:after',
    '.eltdf-blog-pagination ul li.eltdf-pag-active a:after',
    '.eltdf-blog-pag-loading>div',
    '.eltdf-bl-loading>div',
    '.eltdf-drop-down .narrow .second .inner ul',
    '.eltdf-drop-down .wide .second .inner',
    '.eltdf-header-vertical .eltdf-vertical-menu.eltdf-vertical-dropdown-side .second ul',
    '.eltdf-top-bar',
    '.eltdf-search-cover',
    '.eltdf-social-icons-group-widget.eltdf-square-icons .eltdf-social-icon-widget-holder',
    '.eltdf-social-icons-group-widget.eltdf-square-icons .eltdf-social-icon-widget-holder:hover',
    '.eltdf-social-icons-group-widget.eltdf-square-icons.eltdf-light-skin .eltdf-social-icon-widget-holder:hover',
    '.eltdf-pl-standard-pagination ul li a:after',
    '.eltdf-pl-standard-pagination ul li.eltdf-pag-active a:after',
    '.eltdf-pl-loading>div',
    '.eltdf-portfolio-slider-holder .eltdf-portfolio-list-holder.eltdf-pag-light-skin .owl-dots .owl-dot.active span',
    '.eltdf-portfolio-slider-holder .eltdf-portfolio-list-holder.eltdf-pag-light-skin .owl-dots .owl-dot:hover span',
    '.eltdf-portfolio-slider-holder .eltdf-portfolio-list-holder.eltdf-pag-dark-skin .owl-dots .owl-dot.active span',
    '.eltdf-portfolio-slider-holder .eltdf-portfolio-list-holder.eltdf-pag-dark-skin .owl-dots .owl-dot:hover span',
    '.eltdf-testimonials-holder .eltdf-testimonial-text-holder .eltdf-testimonials-separator .eltdf-testimonials-separator-line',
    '.eltdf-dark-header #fp-nav ul li a.active span',
    '.eltdf-dark-header #fp-nav ul li a:hover span',
    '.eltdf-icon-shortcode.eltdf-circle',
    '.eltdf-icon-shortcode.eltdf-dropcaps.eltdf-circle',
    '.eltdf-icon-shortcode.eltdf-square',
    '.eltdf-process-holder .eltdf-process-circle',
    '.eltdf-process-holder .eltdf-process-line',
    '.eltdf-progress-bar .eltdf-pb-content-holder .eltdf-pb-content',
    '.eltdf-separator-holder.eltdf-separator-double-separator .eltdf-separator-line',
    '.swiper-pagination-bullet',
    '.swiper-pagination-black .swiper-pagination-bullet-active',
    '.swiper-pagination-progressbar.swiper-pagination-black .swiper-pagination-progressbar-fill',
    '.swiper-container-cube .swiper-cube-shadow',
    '.eltdf-tabs.eltdf-tabs-boxed .eltdf-tabs-nav li.ui-state-active a',
    '.eltdf-tabs.eltdf-tabs-boxed .eltdf-tabs-nav li.ui-state-hover a',
    '.eltdf-tabs.eltdf-tabs-simple .eltdf-tabs-nav li:after',
    '#multiscroll-nav ul li a.active',
    '.eltdf-dark-header #multiscroll-nav ul li a.active'
);
$background_color_important_selector = array(
    '.eltdf-btn.eltdf-btn-outline:not(.eltdf-btn-custom-hover-bg):hover'
);
$border_color_selector = array(
    'table tbody tr',
    'table thead tr',
    '.eltdf-st-loader .pulse_circles .ball',
    '.eltdf-owl-slider+.eltdf-slider-thumbnail>.eltdf-slider-thumbnail-item.active img',
    '#eltdf-back-to-top>span',
    '#eltdf-back-to-top>span:hover',
    '.wpb_widgetised_column .widget.widget_archive select',
    '.wpb_widgetised_column .widget.widget_categories select',
    '.wpb_widgetised_column .widget.widget_text select',
    'aside.eltdf-sidebar .widget.widget_archive select',
    'aside.eltdf-sidebar .widget.widget_categories select',
    'aside.eltdf-sidebar .widget.widget_text select',
    '.wpb_widgetised_column .widget.eltdf-search-post-type-widget .eltdf-post-type-search-field',
    'aside.eltdf-sidebar .widget.eltdf-search-post-type-widget .eltdf-post-type-search-field',
    '#ui-datepicker-div .ui-widget-header',
    'body .select2-container--default .select2-selection--multiple',
    'body .select2-container--default .select2-search--dropdown .select2-search__field',
    'body .select2-container--default .select2-search--dropdown .select2-search__field:focus',
    '.widget_icl_lang_sel_widget .wpml-ls-legacy-dropdown .wpml-ls-item-toggle',
    '.widget_icl_lang_sel_widget .wpml-ls-legacy-dropdown-click .wpml-ls-item-toggle',
    '.widget_icl_lang_sel_widget .wpml-ls-legacy-dropdown .wpml-ls-sub-menu',
    '.widget_icl_lang_sel_widget .wpml-ls-legacy-dropdown-click .wpml-ls-sub-menu',
    '.eltdf-subscribe-popup-holder .eltdf-sp-prevent-input',
    '.eltdf-top-reviews-carousel-holder',
    '.eltdf-btn.eltdf-btn-outline',
    '.eltdf-social-share-holder.eltdf-dropdown .eltdf-social-share-dropdown ul li',
    '.eltdf-tabs.eltdf-tabs-boxed .eltdf-tabs-nav li',
    '#multiscroll-nav ul li a.active',
    '.eltdf-dark-header #multiscroll-nav ul li a',
    '.eltdf-video-button-holder.eltdf-vb-has-img .eltdf-video-button-play .eltdf-video-button-play-inner .eltdf-button-holder .eltdf-button-play',
    '.eltdf-video-button-holder.eltdf-vb-has-img .eltdf-video-button-play-image .eltdf-video-button-play-inner .eltdf-button-holder .eltdf-button-play',
    'table tbody th',
    '#respond input[type=text],#respond textarea,.eltdf-style-form textarea,.post-password-form input[type=password],.wpcf7-form-control.wpcf7-date,.wpcf7-form-control.wpcf7-number,.wpcf7-form-control.wpcf7-quiz,.wpcf7-form-control.wpcf7-select,.wpcf7-form-control.wpcf7-text,.wpcf7-form-control.wpcf7-textarea,input[type=text],input[type=email],input[type=password]',
    '#respond input[type=text],#respond textarea,.eltdf-style-form textarea,.post-password-form input[type=password],input[type=text],input[type=email],input[type=password]',
    '.wpcf7-form-control.wpcf7-date,.wpcf7-form-control.wpcf7-number,.wpcf7-form-control.wpcf7-quiz,.wpcf7-form-control.wpcf7-select,.wpcf7-form-control.wpcf7-text,.wpcf7-form-control.wpcf7-textarea',
    '.error404 .eltdf-page-not-found .eltdf-404-form .input-holder',
    '.wpb_widgetised_column .widget .eltdf-searchform .input-holder,aside.eltdf-sidebar .widget .eltdf-searchform .input-holder',
    '.eltdf-search-page-holder .eltdf-search-page-form .eltdf-form-holder',
    '.eltdf-search-page-holder article',
    '.eltdf-accordion-holder.eltdf-ac-boxed .eltdf-accordion-title.ui-state-active',
    '.eltdf-pricing-tables:before',
    '.eltdf-pricing-tables:after',
    '.eltdf-tabs.eltdf-tabs-standard .eltdf-tabs-nav li.ui-state-active',
    '.eltdf-tabs.eltdf-tabs-vertical .eltdf-tabs-nav'
);
$border_important_color_selector = array(
    '.eltdf-btn.eltdf-btn-solid:not(.eltdf-btn-custom-border-hover):hover',
    '.eltdf-btn.eltdf-btn-outline:not(.eltdf-btn-custom-border-hover):hover'
);