<?php
$woo_color_selector = array(
    '.woocommerce-page .eltdf-content input:focus[type=text]',
    '.woocommerce-page .eltdf-content input:focus[type=email]',
    '.woocommerce-page .eltdf-content input:focus[type=tel]',
    '.woocommerce-page .eltdf-content input:focus[type=password]',
    '.woocommerce-page .eltdf-content textarea:focus',
    'div.woocommerce input:focus[type=text]',
    'div.woocommerce input:focus[type=email]',
    'div.woocommerce input:focus[type=tel]',
    'div.woocommerce input:focus[type=password]',
    'div.woocommerce textarea:focus',
    '.eltdf-pl-holder .eltdf-pli .eltdf-pli-rating',
    '.eltdf-plc-holder .eltdf-plc-item .eltdf-plc-rating',
    '.eltdf-pls-holder .eltdf-pls-text .eltdf-pls-rating',
    '.eltdf-product-info .eltdf-pi-rating',
    '.eltdf-woo-single-page .woocommerce-tabs #reviews .comment-respond .stars a.active:after',
    '.eltdf-woo-single-page .woocommerce-tabs #reviews .comment-respond .stars a:before',
    '.woocommerce .star-rating',
    '.eltdf-woocommerce-page table.cart thead tr th',
    '.eltdf-woocommerce-page table.cart tr.cart_item td.product-remove a:hover',
    '.eltdf-woocommerce-page .cart-collaterals table th',
    '.eltdf-woocommerce-page .cart-collaterals table td strong',
    '.eltdf-woocommerce-page .cart-empty',
    '.eltdf-woocommerce-page .woocommerce-checkout table td strong',
    '.eltdf-woocommerce-page .woocommerce-checkout table th',
    '.eltdf-woocommerce-page.woocommerce-order-received .woocommerce ul.order_details li strong',
    '.woocommerce .eltdf-new-product',
    '.woocommerce .eltdf-onsale',
    '.woocommerce .eltdf-out-of-stock',
    '.eltdf-woocommerce-page .woocommerce-error>a:hover',
    '.eltdf-woocommerce-page .woocommerce-info>a:hover',
    '.eltdf-woocommerce-page .woocommerce-message>a:hover',
    '.eltdf-woocommerce-page .woocommerce-info .showcoupon:hover',
    '.woocommerce-pagination ul li.eltdf-pag-active a',
    '.woocommerce-pagination ul li span',
    '.woocommerce-pagination ul li span.current',
    '.woocommerce-page .eltdf-content .eltdf-quantity-buttons .eltdf-quantity-minus:hover',
    '.woocommerce-page .eltdf-content .eltdf-quantity-buttons .eltdf-quantity-plus:hover',
    'div.woocommerce .eltdf-quantity-buttons .eltdf-quantity-minus:hover',
    'div.woocommerce .eltdf-quantity-buttons .eltdf-quantity-plus:hover',
    '.eltdf-woocommerce-page .eltdf-content .variations .reset_variations',
    '.eltdf-woocommerce-page .eltdf-content table.group_table a:hover',
    '.eltdf-woocommerce-page.woocommerce-account .woocommerce form.edit-account fieldset>legend',
    '.eltdf-woocommerce-page.woocommerce-account .vc_row .woocommerce form.login p label:not(.inline)',
    '.eltdf-woocommerce-page.eltdf-woocommerce-order-tracking .woocommerce>.track_order .form-row-first label',
    '.eltdf-woocommerce-page.eltdf-woocommerce-order-tracking .woocommerce>.track_order .form-row-last label',
    '.eltdf-content .woocommerce.add_to_cart_inline del',
    '.eltdf-content .woocommerce.add_to_cart_inline ins',
    'div.woocommerce>.single-product .woocommerce-tabs table th',
    '.eltdf-woo-single-page .eltdf-single-product-summary .product_meta>span a',
    '.eltdf-woo-single-page .eltdf-single-product-summary .product_meta>span a:hover',
    '.eltdf-woo-single-page .eltdf-single-product-summary .product_meta span a',
    '.eltdf-woo-single-page .eltdf-single-product-summary .product_meta span span',
    '.eltdf-woo-single-page .eltdf-single-product-summary p.stock.in-stock',
    '.eltdf-woo-single-page .eltdf-single-product-summary p.stock.out-of-stock',
    '.eltdf-woo-single-page .woocommerce-tabs ul.tabs>li a',
    '.eltdf-woo-single-page .woocommerce-tabs table td',
    '.eltdf-woo-single-page .woocommerce-tabs #reviews h2',
    '.eltdf-woo-single-page .woocommerce-tabs #reviews .comment-respond .comment-reply-title',
    '.eltdf-shopping-cart-holder .eltdf-header-cart .eltdf-cart-number',
    '.eltdf-dark-header .eltdf-page-header>div:not(.eltdf-sticky-header):not(.fixed) .eltdf-shopping-cart-holder .eltdf-header-cart',
    '.eltdf-dark-header .eltdf-page-header>div:not(.eltdf-sticky-header):not(.fixed) .eltdf-shopping-cart-holder .eltdf-header-cart:hover',
    '.eltdf-light-header .eltdf-page-header>div:not(.eltdf-sticky-header):not(.fixed) .eltdf-shopping-cart-holder .eltdf-header-cart:hover',
    '.eltdf-shopping-cart-dropdown .eltdf-cart-bottom .eltdf-view-cart:hover',
    '.eltdf-shopping-cart-dropdown .eltdf-cart-bottom .eltdf-checkout',
    '.eltdf-shopping-cart-dropdown .eltdf-cart-bottom .eltdf-subtotal-holder>*',
    '.widget.woocommerce.widget_layered_nav .chosen a',
    '.eltdf-product-info .eltdf-pi-add-to-cart .eltdf-btn.eltdf-btn-solid.eltdf-white-skin',
    '.eltdf-product-info .eltdf-pi-add-to-cart .eltdf-btn.eltdf-btn-solid.eltdf-dark-skin:hover',
    '.eltdf-plc-holder .eltdf-plc-item .eltdf-plc-image-outer .eltdf-plc-image .eltdf-plc-new-product',
    '.eltdf-plc-holder .eltdf-plc-item .eltdf-plc-image-outer .eltdf-plc-image .eltdf-plc-onsale',
    '.eltdf-plc-holder .eltdf-plc-item .eltdf-plc-image-outer .eltdf-plc-image .eltdf-plc-out-of-stock',
    '.eltdf-plc-holder .eltdf-plc-item .eltdf-plc-excerpt',
    '.eltdf-plc-holder .eltdf-plc-item .eltdf-plc-add-to-cart.eltdf-light-skin .added_to_cart',
    '.eltdf-plc-holder .eltdf-plc-item .eltdf-plc-add-to-cart.eltdf-light-skin .button',
    '.eltdf-plc-holder.eltdf-plc-nav-light-skin .owl-nav .owl-next:hover',
    '.eltdf-plc-holder.eltdf-plc-nav-light-skin .owl-nav .owl-prev:hover',
    '.eltdf-pl-holder .eltdf-pli .eltdf-pli-excerpt',
    '.eltdf-pl-holder .eltdf-pli-inner .eltdf-pli-image .eltdf-pli-new-product',
    '.eltdf-pl-holder .eltdf-pli-inner .eltdf-pli-image .eltdf-pli-onsale',
    '.eltdf-pl-holder .eltdf-pli-inner .eltdf-pli-image .eltdf-pli-out-of-stock',
    '.eltdf-pl-holder .eltdf-pli-inner .eltdf-pli-text-inner .eltdf-pli-add-to-cart.eltdf-light-skin .added_to_cart',
    '.eltdf-pl-holder .eltdf-pli-inner .eltdf-pli-text-inner .eltdf-pli-add-to-cart.eltdf-light-skin .button',
    '.eltdf-pl-holder.eltdf-product-info-dark .eltdf-pli-inner .eltdf-pli-text-inner .eltdf-pli-category a',
    '.eltdf-pl-holder.eltdf-product-info-dark .eltdf-pli-inner .eltdf-pli-text-inner .eltdf-pli-excerpt',
    '.eltdf-pl-holder.eltdf-product-info-dark .eltdf-pli-inner .eltdf-pli-text-inner .eltdf-pli-price',
    '.eltdf-pl-holder.eltdf-product-info-dark .eltdf-pli-inner .eltdf-pli-text-inner .eltdf-pli-rating',
    '.eltdf-pl-holder.eltdf-product-info-dark .eltdf-pli-inner .eltdf-pli-text-inner .eltdf-pli-title',
    '.eltdf-pp-holder .eltdf-ppi .eltdf-ppi-inner .eltdf-ppi-text-wrapper .eltdf-eltdf-big-product-add-to-cart a:hover',
    '.eltdf-pp-holder .eltdf-ppi .eltdf-ppi-inner .eltdf-ppi-text-wrapper .eltdf-eltdf-small-product-add-to-cart a:hover'
);
$woo_background_color_selector = array(
    '.woocommerce-page .eltdf-content .wc-forward:not(.added_to_cart):not(.checkout-button):hover',
    '.woocommerce-page .eltdf-content a.added_to_cart:hover',
    '.woocommerce-page .eltdf-content a.button:hover',
    '.woocommerce-page .eltdf-content button[type=submit]:not(.eltdf-search-submit):hover',
    '.woocommerce-page .eltdf-content input[type=submit]:hover',
    'div.woocommerce .wc-forward:not(.added_to_cart):not(.checkout-button):hover',
    'div.woocommerce a.added_to_cart:hover',
    'div.woocommerce a.button:hover',
    'div.woocommerce button[type=submit]:not(.eltdf-search-submit):hover',
    'div.woocommerce input[type=submit]:hover',
    '.woocommerce-pagination ul li a:after',
    '.woocommerce-pagination ul li.eltdf-pag-active a:after',
    '.woocommerce-pagination ul li span.current:after',
    '.eltdf-woo-single-page .woocommerce-tabs ul.tabs>li:after',
    '.eltdf-shopping-cart-dropdown',
    '.widget.woocommerce.widget_price_filter .price_slider_wrapper .ui-widget-content .ui-slider-handle',
    '.widget.woocommerce.widget_price_filter .price_slider_amount .button:after',
    '.widget.woocommerce.widget_shopping_cart .buttons .button:hover',
    '.eltdf-product-info .eltdf-pi-add-to-cart .eltdf-btn.eltdf-btn-solid.eltdf-dark-skin',
    '.eltdf-product-info .eltdf-pi-add-to-cart .eltdf-btn.eltdf-btn-solid.eltdf-white-skin:hover',
    '.eltdf-plc-holder .eltdf-plc-item .eltdf-plc-add-to-cart.eltdf-default-skin .added_to_cart:hover',
    '.eltdf-plc-holder .eltdf-plc-item .eltdf-plc-add-to-cart.eltdf-default-skin .button:hover',
    '.eltdf-plc-holder .eltdf-plc-item .eltdf-plc-add-to-cart.eltdf-dark-skin .added_to_cart',
    '.eltdf-plc-holder .eltdf-plc-item .eltdf-plc-add-to-cart.eltdf-dark-skin .added_to_cart:hover',
    '.eltdf-plc-holder .eltdf-plc-item .eltdf-plc-add-to-cart.eltdf-dark-skin .button',
    '.eltdf-plc-holder .eltdf-plc-item .eltdf-plc-add-to-cart.eltdf-dark-skin .button:hover',
    '.eltdf-plc-holder .eltdf-plc-item .eltdf-plc-add-to-cart.eltdf-light-skin .added_to_cart:hover',
    '.eltdf-plc-holder .eltdf-plc-item .eltdf-plc-add-to-cart.eltdf-light-skin .button:hover',
    '.eltdf-plc-holder.eltdf-plc-pag-light-skin .owl-dots .owl-dot span',
    '.eltdf-pl-holder .eltdf-pli-inner .eltdf-pli-text-inner .eltdf-pli-add-to-cart.eltdf-default-skin .added_to_cart:hover',
    '.eltdf-pl-holder .eltdf-pli-inner .eltdf-pli-text-inner .eltdf-pli-add-to-cart.eltdf-default-skin .button:hover',
    '.eltdf-pl-holder .eltdf-pli-inner .eltdf-pli-text-inner .eltdf-pli-add-to-cart.eltdf-dark-skin .added_to_cart',
    '.eltdf-pl-holder .eltdf-pli-inner .eltdf-pli-text-inner .eltdf-pli-add-to-cart.eltdf-dark-skin .added_to_cart:hover',
    '.eltdf-pl-holder .eltdf-pli-inner .eltdf-pli-text-inner .eltdf-pli-add-to-cart.eltdf-dark-skin .button',
    '.eltdf-pl-holder .eltdf-pli-inner .eltdf-pli-text-inner .eltdf-pli-add-to-cart.eltdf-dark-skin .button:hover',
    '.eltdf-pl-holder .eltdf-pli-inner .eltdf-pli-text-inner .eltdf-pli-add-to-cart.eltdf-light-skin .added_to_cart:hover',
    '.eltdf-pl-holder .eltdf-pli-inner .eltdf-pli-text-inner .eltdf-pli-add-to-cart.eltdf-light-skin .button:hover',
    '.eltdf-pp-holder .eltdf-ppi .eltdf-ppi-inner .eltdf-ppi-text .eltdf-ppi-text-inner .eltdf-yith-wcqv-holder a'
);
$woo_border_color_selector = array(
    '.eltdf-shopping-cart-dropdown',
    '.eltdf-product-info .eltdf-pi-add-to-cart .eltdf-btn.eltdf-btn-solid.eltdf-dark-skin',
    '.eltdf-product-info .eltdf-pi-add-to-cart .eltdf-btn.eltdf-btn-solid.eltdf-white-skin:hover',
    '.woocommerce-page .eltdf-content input[type=text],.woocommerce-page .eltdf-content input[type=email],.woocommerce-page .eltdf-content input[type=tel],.woocommerce-page .eltdf-content input[type=password],.woocommerce-page .eltdf-content textarea,div.woocommerce input[type=text],div.woocommerce input[type=email],div.woocommerce input[type=tel],div.woocommerce input[type=password],div.woocommerce textarea',
    '.eltdf-woocommerce-page table.cart thead tr',
    '.eltdf-woocommerce-page table.cart tr.cart_item',
    '.eltdf-woocommerce-page .cart-collaterals table tr',
    '.eltdf-woocommerce-page .cross-sells',
    '.eltdf-woocommerce-page.woocommerce-order-received .woocommerce ul.order_details li',
    '.eltdf-woocommerce-page.woocommerce-order-received .woocommerce table.shop_table tr',
    '.eltdf-woocommerce-page.woocommerce-account .woocommerce-MyAccount-navigation ul',
    '.eltdf-woocommerce-page.woocommerce-account .woocommerce table.shop_table tr',
    'div.woocommerce>.single-product .woocommerce-tabs ul.tabs',
    'div.woocommerce>.single-product .woocommerce-tabs ul.tabs',
    'div.woocommerce>.single-product .related.products,div.woocommerce>.single-product .upsells.products',
    '.eltdf-shopping-cart-dropdown ul li:last-child'
);
